name: "Path To Live"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  security-events: write
  pull-requests: write
  actions: none
  checks: none
  deployments: none
  issues: write
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  create_tags:
    name: Create Tags
    uses: ./.github/workflows/tags_job.yml

  docker_build_scan_push:
    name: Docker Build, Scan and Push
    uses: ./.github/workflows/docker_job.yml
    needs: create_tags
    with:
      tag: ${{ needs.create_tags.outputs.version_tag }}
      checkout_tag: ${{ github.head_ref }}
      branch_name: ${{ github.head_ref }}
      timestamp: ${{ needs.create_tags.outputs.timestamp }}


  terraform_account_workflow_development:
    name: TF Apply Dev Account
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      workspace_name: development
      oidc_role_arn: arn:aws:iam::679638075911:role/opg-mrlpa-mc-github-actions-ci-terraform-development

  terraform_account_workflow_production:
    name: TF Apply Dev Account
    uses: ./.github/workflows/terraform_account_job.yml
    needs: terraform_account_workflow_development
    with:
      workspace_name: production
      oidc_role_arn: arn:aws:iam::997462338508:role/opg-mrlpa-mc-github-actions-ci-terraform-production

  production_deploy:
      name: ${{ needs.create_tags.outputs.environment_workspace_name }} Environment Deploy
      needs: [
        create_tags,
        docker_build_scan_push,
        terraform_account_workflow_production,
      ]
      uses: ./.github/workflows/terraform_environment_job.yml
      secrets:
        ssh_deploy_key: ${{ secrets.MRLPA_MC_DEPLOY_KEY_PRIVATE_KEY }}
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        workspace_name: production
        version_tag: ${{ needs.create_tags.outputs.version_tag }}
        oidc_role_arn: arn:aws:iam::997462338508:role/opg-mrlpa-mc-github-actions-ci-terraform-production

  ur_deploy:
      name: ${{ needs.create_tags.outputs.environment_workspace_name }} Environment Deploy
      needs: [
        create_tags,
        docker_build_scan_push,
        terraform_account_workflow_development,
      ]
      uses: ./.github/workflows/terraform_environment_job.yml
      secrets:
        ssh_deploy_key: ${{ secrets.MRLPA_MC_DEPLOY_KEY_PRIVATE_KEY }}
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        workspace_name: ur
        version_tag: ${{ needs.create_tags.outputs.version_tag }}
        oidc_role_arn: arn:aws:iam::679638075911:role/opg-mrlpa-mc-github-actions-ci-terraform-development

  end_of_pr_workflow:
    name: End of PR Workflow
    runs-on: ubuntu-latest
    needs: [
      docker_build_scan_push,
      terraform_account_workflow_development,
      production_deploy,
    ]
    if: always()
    steps:
      - name: End of PR Workflow
        run: |
          echo "End of workflow"
